// AUTOGENERATED FILE: easyjson marshaller/unmarshallers.

package glTF

import (
	json "encoding/json"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ = json.RawMessage{}
	_ = jlexer.Lexer{}
	_ = jwriter.Writer{}
)

func easyjson16127c7DecodeGithubComSturfeeincGlTF(in *jlexer.Lexer, out *AnimationChannel) {
	if in.IsNull() {
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "sampler":
			out.Sampler = GlTFid(in.String())
		case "target":
			(out.Target).UnmarshalEasyJSON(in)
		case "extensions":
			out.Extensions = in.Interface()
		case "extras":
			out.Extras = in.Interface()
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
}
func easyjson16127c7EncodeGithubComSturfeeincGlTF(out *jwriter.Writer, in AnimationChannel) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Sampler != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"sampler\":")
		out.String(string(in.Sampler))
	}
	if true {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"target\":")
		(in.Target).MarshalEasyJSON(out)
	}
	if in.Extensions != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"extensions\":")
		out.Raw(json.Marshal(in.Extensions))
	}
	if in.Extras != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"extras\":")
		out.Raw(json.Marshal(in.Extras))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AnimationChannel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson16127c7EncodeGithubComSturfeeincGlTF(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AnimationChannel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson16127c7EncodeGithubComSturfeeincGlTF(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AnimationChannel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson16127c7DecodeGithubComSturfeeincGlTF(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AnimationChannel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson16127c7DecodeGithubComSturfeeincGlTF(l, v)
}
