// AUTOGENERATED FILE: easyjson marshaller/unmarshallers.

package glTF

import (
	json "encoding/json"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ = json.RawMessage{}
	_ = jlexer.Lexer{}
	_ = jwriter.Writer{}
)

func easyjson5981eb96DecodeGithubComSturfeeincGlTF(in *jlexer.Lexer, out *AnimationSampler) {
	if in.IsNull() {
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "input":
			out.Input = GlTFid(in.String())
		case "interpolation":
			out.Interpolation = string(in.String())
		case "output":
			out.Output = GlTFid(in.String())
		case "extensions":
			out.Extensions = in.Interface()
		case "extras":
			out.Extras = in.Interface()
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
}
func easyjson5981eb96EncodeGithubComSturfeeincGlTF(out *jwriter.Writer, in AnimationSampler) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Input != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"input\":")
		out.String(string(in.Input))
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"interpolation\":")
	out.String(string(in.Interpolation))
	if in.Output != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"output\":")
		out.String(string(in.Output))
	}
	if in.Extensions != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"extensions\":")
		out.Raw(json.Marshal(in.Extensions))
	}
	if in.Extras != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"extras\":")
		out.Raw(json.Marshal(in.Extras))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AnimationSampler) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5981eb96EncodeGithubComSturfeeincGlTF(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AnimationSampler) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5981eb96EncodeGithubComSturfeeincGlTF(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AnimationSampler) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5981eb96DecodeGithubComSturfeeincGlTF(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AnimationSampler) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5981eb96DecodeGithubComSturfeeincGlTF(l, v)
}
