// AUTOGENERATED FILE: easyjson marshaller/unmarshallers.

package glTF

import (
	json "encoding/json"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ = json.RawMessage{}
	_ = jlexer.Lexer{}
	_ = jwriter.Writer{}
)

func easyjsonD426198fDecodeGithubComSturfeeincGlTF(in *jlexer.Lexer, out *CameraOrthographic) {
	if in.IsNull() {
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "znear":
			out.Znear = float64(in.Float64())
		case "xmag":
			out.Xmag = float64(in.Float64())
		case "ymag":
			out.Ymag = float64(in.Float64())
		case "zfar":
			out.Zfar = float64(in.Float64())
		case "extensions":
			out.Extensions = in.Interface()
		case "extras":
			out.Extras = in.Interface()
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
}
func easyjsonD426198fEncodeGithubComSturfeeincGlTF(out *jwriter.Writer, in CameraOrthographic) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Znear != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"znear\":")
		out.Float64(float64(in.Znear))
	}
	if in.Xmag != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"xmag\":")
		out.Float64(float64(in.Xmag))
	}
	if in.Ymag != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"ymag\":")
		out.Float64(float64(in.Ymag))
	}
	if in.Zfar != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"zfar\":")
		out.Float64(float64(in.Zfar))
	}
	if in.Extensions != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"extensions\":")
		out.Raw(json.Marshal(in.Extensions))
	}
	if in.Extras != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"extras\":")
		out.Raw(json.Marshal(in.Extras))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CameraOrthographic) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD426198fEncodeGithubComSturfeeincGlTF(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CameraOrthographic) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD426198fEncodeGithubComSturfeeincGlTF(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CameraOrthographic) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD426198fDecodeGithubComSturfeeincGlTF(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CameraOrthographic) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD426198fDecodeGithubComSturfeeincGlTF(l, v)
}
