// AUTOGENERATED FILE: easyjson marshaller/unmarshallers.

package glTF

import (
	json "encoding/json"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ = json.RawMessage{}
	_ = jlexer.Lexer{}
	_ = jwriter.Writer{}
)

func easyjsonB390058DecodeGithubComSturfeeincGlTF(in *jlexer.Lexer, out *MeshPrimitive) {
	if in.IsNull() {
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "attributes":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Attributes = make(map[string]MeshPrimitiveAttribute)
				} else {
					out.Attributes = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 MeshPrimitiveAttribute
					v1 = in.Interface()
					(out.Attributes)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		case "indices":
			out.Indices = GlTFid(in.String())
		case "material":
			out.Material = GlTFid(in.String())
		case "mode":
			out.Mode = int(in.Int())
		case "extensions":
			out.Extensions = in.Interface()
		case "extras":
			out.Extras = in.Interface()
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
}
func easyjsonB390058EncodeGithubComSturfeeincGlTF(out *jwriter.Writer, in MeshPrimitive) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"attributes\":")
	if in.Attributes == nil {
		out.RawString(`null`)
	} else {
		out.RawByte('{')
		v2First := true
		for v2Name, v2Value := range in.Attributes {
			if !v2First {
				out.RawByte(',')
			}
			v2First = false
			out.String(string(v2Name))
			out.RawByte(':')
			out.Raw(json.Marshal(v2Value))
		}
		out.RawByte('}')
	}
	if in.Indices != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"indices\":")
		out.String(string(in.Indices))
	}
	if in.Material != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"material\":")
		out.String(string(in.Material))
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"mode\":")
	out.Int(int(in.Mode))
	if in.Extensions != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"extensions\":")
		out.Raw(json.Marshal(in.Extensions))
	}
	if in.Extras != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"extras\":")
		out.Raw(json.Marshal(in.Extras))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MeshPrimitive) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB390058EncodeGithubComSturfeeincGlTF(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MeshPrimitive) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB390058EncodeGithubComSturfeeincGlTF(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MeshPrimitive) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB390058DecodeGithubComSturfeeincGlTF(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MeshPrimitive) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB390058DecodeGithubComSturfeeincGlTF(l, v)
}
