// AUTOGENERATED FILE: easyjson marshaller/unmarshallers.

package glTF

import (
	json "encoding/json"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ = json.RawMessage{}
	_ = jlexer.Lexer{}
	_ = jwriter.Writer{}
)

func easyjsonA2668feeDecodeGithubComSturfeeincGlTF(in *jlexer.Lexer, out *Sampler) {
	if in.IsNull() {
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "magFilter":
			out.MagFilter = int(in.Int())
		case "minFilter":
			out.MinFilter = int(in.Int())
		case "wrapS":
			out.WrapS = int(in.Int())
		case "wrapT":
			out.WrapT = int(in.Int())
		case "name":
			out.Name = string(in.String())
		case "extensions":
			out.Extensions = in.Interface()
		case "extras":
			out.Extras = in.Interface()
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
}
func easyjsonA2668feeEncodeGithubComSturfeeincGlTF(out *jwriter.Writer, in Sampler) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"magFilter\":")
	out.Int(int(in.MagFilter))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"minFilter\":")
	out.Int(int(in.MinFilter))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"wrapS\":")
	out.Int(int(in.WrapS))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"wrapT\":")
	out.Int(int(in.WrapT))
	if in.Name != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"name\":")
		out.String(string(in.Name))
	}
	if in.Extensions != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"extensions\":")
		out.Raw(json.Marshal(in.Extensions))
	}
	if in.Extras != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"extras\":")
		out.Raw(json.Marshal(in.Extras))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Sampler) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA2668feeEncodeGithubComSturfeeincGlTF(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Sampler) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA2668feeEncodeGithubComSturfeeincGlTF(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Sampler) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA2668feeDecodeGithubComSturfeeincGlTF(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Sampler) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA2668feeDecodeGithubComSturfeeincGlTF(l, v)
}
