// AUTOGENERATED FILE: easyjson marshaller/unmarshallers.

package glTF

import (
	json "encoding/json"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ = json.RawMessage{}
	_ = jlexer.Lexer{}
	_ = jwriter.Writer{}
)

func easyjson9c326fb7DecodeGithubComSturfeeincGlTF(in *jlexer.Lexer, out *Skin) {
	if in.IsNull() {
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "bindShapeMatrix":
			in.Delim('[')
			if !in.IsDelim(']') {
				out.BindShapeMatrix = make([]float64, 0, 8)
			} else {
				out.BindShapeMatrix = nil
			}
			for !in.IsDelim(']') {
				var v1 float64
				v1 = float64(in.Float64())
				out.BindShapeMatrix = append(out.BindShapeMatrix, v1)
				in.WantComma()
			}
			in.Delim(']')
		case "inverseBindMatrices":
			out.InverseBindMatrices = GlTFid(in.String())
		case "jointNames":
			in.Delim('[')
			if !in.IsDelim(']') {
				out.JointNames = make([]GlTFid, 0, 4)
			} else {
				out.JointNames = nil
			}
			for !in.IsDelim(']') {
				var v2 GlTFid
				v2 = GlTFid(in.String())
				out.JointNames = append(out.JointNames, v2)
				in.WantComma()
			}
			in.Delim(']')
		case "name":
			out.Name = string(in.String())
		case "extensions":
			out.Extensions = in.Interface()
		case "extras":
			out.Extras = in.Interface()
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
}
func easyjson9c326fb7EncodeGithubComSturfeeincGlTF(out *jwriter.Writer, in Skin) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"bindShapeMatrix\":")
	out.RawByte('[')
	for v3, v4 := range in.BindShapeMatrix {
		if v3 > 0 {
			out.RawByte(',')
		}
		out.Float64(float64(v4))
	}
	out.RawByte(']')
	if in.InverseBindMatrices != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"inverseBindMatrices\":")
		out.String(string(in.InverseBindMatrices))
	}
	if len(in.JointNames) != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"jointNames\":")
		out.RawByte('[')
		for v5, v6 := range in.JointNames {
			if v5 > 0 {
				out.RawByte(',')
			}
			out.String(string(v6))
		}
		out.RawByte(']')
	}
	if in.Name != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"name\":")
		out.String(string(in.Name))
	}
	if in.Extensions != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"extensions\":")
		out.Raw(json.Marshal(in.Extensions))
	}
	if in.Extras != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"extras\":")
		out.Raw(json.Marshal(in.Extras))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Skin) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9c326fb7EncodeGithubComSturfeeincGlTF(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Skin) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9c326fb7EncodeGithubComSturfeeincGlTF(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Skin) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9c326fb7DecodeGithubComSturfeeincGlTF(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Skin) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9c326fb7DecodeGithubComSturfeeincGlTF(l, v)
}
