// AUTOGENERATED FILE: easyjson marshaller/unmarshallers.

package glTF

import (
	json "encoding/json"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ = json.RawMessage{}
	_ = jlexer.Lexer{}
	_ = jwriter.Writer{}
)

func easyjsonD7672b78DecodeGithubComSturfeeincGlTF(in *jlexer.Lexer, out *TechniqueParameters) {
	if in.IsNull() {
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "count":
			out.Count = int(in.Int())
		case "node":
			out.Node = GlTFid(in.String())
		case "type":
			out.Type = int(in.Int())
		case "semantic":
			out.Semantic = string(in.String())
		case "value":
			out.Value = in.Interface()
		case "extensions":
			out.Extensions = in.Interface()
		case "extras":
			out.Extras = in.Interface()
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
}
func easyjsonD7672b78EncodeGithubComSturfeeincGlTF(out *jwriter.Writer, in TechniqueParameters) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"count\":")
	out.Int(int(in.Count))
	if in.Node != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"node\":")
		out.String(string(in.Node))
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"type\":")
	out.Int(int(in.Type))
	if in.Semantic != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"semantic\":")
		out.String(string(in.Semantic))
	}
	if in.Value != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"value\":")
		out.Raw(json.Marshal(in.Value))
	}
	if in.Extensions != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"extensions\":")
		out.Raw(json.Marshal(in.Extensions))
	}
	if in.Extras != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"extras\":")
		out.Raw(json.Marshal(in.Extras))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TechniqueParameters) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD7672b78EncodeGithubComSturfeeincGlTF(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TechniqueParameters) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD7672b78EncodeGithubComSturfeeincGlTF(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TechniqueParameters) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD7672b78DecodeGithubComSturfeeincGlTF(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TechniqueParameters) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD7672b78DecodeGithubComSturfeeincGlTF(l, v)
}
