// AUTOGENERATED FILE: easyjson marshaller/unmarshallers.

package glTF

import (
	json "encoding/json"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ = json.RawMessage{}
	_ = jlexer.Lexer{}
	_ = jwriter.Writer{}
)

func easyjson1b4f51fDecodeGithubComSturfeeincGlTF(in *jlexer.Lexer, out *Texture) {
	if in.IsNull() {
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "source":
			out.Source = GlTFid(in.String())
		case "target":
			out.Target = int(in.Int())
		case "type":
			out.Type = int(in.Int())
		case "format":
			out.Format = int(in.Int())
		case "internalFormat":
			out.InternalFormat = int(in.Int())
		case "sampler":
			out.Sampler = GlTFid(in.String())
		case "name":
			out.Name = string(in.String())
		case "extensions":
			out.Extensions = in.Interface()
		case "extras":
			out.Extras = in.Interface()
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
}
func easyjson1b4f51fEncodeGithubComSturfeeincGlTF(out *jwriter.Writer, in Texture) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Source != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"source\":")
		out.String(string(in.Source))
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"target\":")
	out.Int(int(in.Target))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"type\":")
	out.Int(int(in.Type))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"format\":")
	out.Int(int(in.Format))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"internalFormat\":")
	out.Int(int(in.InternalFormat))
	if in.Sampler != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"sampler\":")
		out.String(string(in.Sampler))
	}
	if in.Name != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"name\":")
		out.String(string(in.Name))
	}
	if in.Extensions != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"extensions\":")
		out.Raw(json.Marshal(in.Extensions))
	}
	if in.Extras != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"extras\":")
		out.Raw(json.Marshal(in.Extras))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Texture) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1b4f51fEncodeGithubComSturfeeincGlTF(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Texture) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1b4f51fEncodeGithubComSturfeeincGlTF(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Texture) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1b4f51fDecodeGithubComSturfeeincGlTF(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Texture) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1b4f51fDecodeGithubComSturfeeincGlTF(l, v)
}
