// AUTOGENERATED FILE: easyjson marshaller/unmarshallers.

package glTF

import (
	json "encoding/json"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ = json.RawMessage{}
	_ = jlexer.Lexer{}
	_ = jwriter.Writer{}
)

func easyjson4659fa09DecodeGithubComSturfeeincGlTF(in *jlexer.Lexer, out *BufferView) {
	if in.IsNull() {
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "target":
			out.Target = int(in.Int())
		case "buffer":
			out.Buffer = GlTFid(in.String())
		case "byteOffset":
			out.ByteOffset = int(in.Int())
		case "byteLength":
			out.ByteLength = int(in.Int())
		case "name":
			out.Name = string(in.String())
		case "extensions":
			out.Extensions = in.Interface()
		case "extras":
			out.Extras = in.Interface()
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
}
func easyjson4659fa09EncodeGithubComSturfeeincGlTF(out *jwriter.Writer, in BufferView) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"target\":")
	out.Int(int(in.Target))
	if in.Buffer != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"buffer\":")
		out.String(string(in.Buffer))
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"byteOffset\":")
	out.Int(int(in.ByteOffset))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"byteLength\":")
	out.Int(int(in.ByteLength))
	if in.Name != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"name\":")
		out.String(string(in.Name))
	}
	if in.Extensions != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"extensions\":")
		out.Raw(json.Marshal(in.Extensions))
	}
	if in.Extras != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"extras\":")
		out.Raw(json.Marshal(in.Extras))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BufferView) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4659fa09EncodeGithubComSturfeeincGlTF(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BufferView) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4659fa09EncodeGithubComSturfeeincGlTF(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BufferView) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4659fa09DecodeGithubComSturfeeincGlTF(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BufferView) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4659fa09DecodeGithubComSturfeeincGlTF(l, v)
}
