// AUTOGENERATED FILE: easyjson marshaller/unmarshallers.

package glTF

import (
	json "encoding/json"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ = json.RawMessage{}
	_ = jlexer.Lexer{}
	_ = jwriter.Writer{}
)

func easyjsonBd6969d3DecodeGithubComSturfeeincGlTF(in *jlexer.Lexer, out *Mesh) {
	if in.IsNull() {
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "primitives":
			in.Delim('[')
			if !in.IsDelim(']') {
				out.Primitives = make([]MeshPrimitive, 0, 1)
			} else {
				out.Primitives = nil
			}
			for !in.IsDelim(']') {
				var v1 MeshPrimitive
				(v1).UnmarshalEasyJSON(in)
				out.Primitives = append(out.Primitives, v1)
				in.WantComma()
			}
			in.Delim(']')
		case "name":
			out.Name = string(in.String())
		case "extensions":
			out.Extensions = in.Interface()
		case "extras":
			out.Extras = in.Interface()
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
}
func easyjsonBd6969d3EncodeGithubComSturfeeincGlTF(out *jwriter.Writer, in Mesh) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"primitives\":")
	out.RawByte('[')
	for v2, v3 := range in.Primitives {
		if v2 > 0 {
			out.RawByte(',')
		}
		(v3).MarshalEasyJSON(out)
	}
	out.RawByte(']')
	if in.Name != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"name\":")
		out.String(string(in.Name))
	}
	if in.Extensions != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"extensions\":")
		out.Raw(json.Marshal(in.Extensions))
	}
	if in.Extras != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"extras\":")
		out.Raw(json.Marshal(in.Extras))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Mesh) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBd6969d3EncodeGithubComSturfeeincGlTF(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Mesh) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBd6969d3EncodeGithubComSturfeeincGlTF(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Mesh) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBd6969d3DecodeGithubComSturfeeincGlTF(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Mesh) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBd6969d3DecodeGithubComSturfeeincGlTF(l, v)
}
